<a href="https://colab.research.google.com/github/juyounLee/DeepLearningZeroToAll_TF2./blob/main/04_1_Multi_Variable_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

### Data
- x1 (quiz 1)	x2 (quiz 2)	x3 (mid 1)	Y (final)
- 73	         80	         75	        152
- 93	         88	         93	        185
- 89	         91	         90	        180
- 96	         98	         100	      196
- 73	         66	         70	        142

In [2]:
# x and y data
x1 = [73., 93., 89., 96., 73.]
x2 = [80., 88., 91., 98., 66]
x3 = [75., 93., 90., 100., 70.]
y = [152., 185., 180., 196., 142.]

In [3]:
# initialize the variables
#w1 = tf.Variable(tf.random.normal([1], -10, 10))
#w2 = tf.Variable(tf.random.normal([1], -10, 10))
#w3 = tf.Variable(tf.random.normal([1], -10, 10))
#b = tf.Variable(tf.random.normal([1], -10, 10))

w1 = tf.Variable(10.)
w2 = tf.Variable(10.)
w3 = tf.Variable(10.)
b = tf.Variable(10.)


In [4]:
# train the data

learning_rate = 0.000001

for i in range(1001):
  with tf.GradientTape() as tape:
    hypothesis = w1*x1 + w2*x2 + w3*x3 + b
    cost = tf.reduce_mean(tf.square(hypothesis - y))

  # calculate the gradient of variables
  w1_grad, w2_grad, w3_grad, b_grad = tape.gradient(cost, [w1, w2, w3, b])
  
  # update the variables
  w1.assign_sub(learning_rate*w1_grad)
  w2.assign_sub(learning_rate*w2_grad)
  w3.assign_sub(learning_rate*w3_grad)
  b.assign_sub(learning_rate*b_grad)

  if i % 50 == 0:
    print('i: {:6}  cost: {:12.6f}'.format(i, cost.numpy()))

i:      0  cost: 5793889.500000
i:     50  cost: 64291.156250
i:    100  cost:   715.290344
i:    150  cost:     9.846125
i:    200  cost:     2.015248
i:    250  cost:     1.925177
i:    300  cost:     1.920982
i:    350  cost:     1.917734
i:    400  cost:     1.914541
i:    450  cost:     1.911373
i:    500  cost:     1.908144
i:    550  cost:     1.904979
i:    600  cost:     1.901804
i:    650  cost:     1.898633
i:    700  cost:     1.895486
i:    750  cost:     1.892339
i:    800  cost:     1.889200
i:    850  cost:     1.886062
i:    900  cost:     1.882930
i:    950  cost:     1.879774
i:   1000  cost:     1.876694


### Multi Variable with Matrix

In [23]:
data = np.array([
    # X1,   X2,    X3,   y
    [ 73.,  80.,  75., 152. ],
    [ 93.,  88.,  93., 185. ],
    [ 89.,  91.,  90., 180. ],
    [ 96.,  98., 100., 196. ],
    [ 73.,  66.,  70., 142. ]
], dtype=np.float32)

In [24]:
x = data[:, :-1]
y = data[:, [-1]]

In [25]:
# initialize the variables

W = tf.Variable(tf.random.normal([3, 1]))
b = tf.Variable(tf.random.normal([1]))

print(W)
print(x.shape)
print(W.shape)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.0066725 ],
       [1.1733797 ],
       [0.40391317]], dtype=float32)>
(5, 3)
(3, 1)


In [28]:
# train the data
learning_rate = 0.000001
print('epoch | cost')

for i in range(2001):
  with tf.GradientTape() as tape:
    hypothesis = tf.matmul(x, W) + b
    cost = tf.reduce_mean(tf.square(hypothesis - y))

  # calculate the gradient of variables
  W_grad, b_grad = tape.gradient(cost, [W, b])

  # update the variables
  W.assign_sub(learning_rate*W_grad)
  b.assign_sub(learning_rate*b_grad)

  if i % 100 == 0:
    print('i: {:6}  cost: {:12.6f}'.format(i, cost.numpy()))

epoch | cost
i:      0  cost:  2211.163818
i:    100  cost:     4.311399
i:    200  cost:     4.018947
i:    300  cost:     3.998309
i:    400  cost:     3.977823
i:    500  cost:     3.957447
i:    600  cost:     3.937177
i:    700  cost:     3.917018
i:    800  cost:     3.896954
i:    900  cost:     3.877033
i:   1000  cost:     3.857217
i:   1100  cost:     3.837500
i:   1200  cost:     3.817873
i:   1300  cost:     3.798364
i:   1400  cost:     3.778953
i:   1500  cost:     3.759661
i:   1600  cost:     3.740466
i:   1700  cost:     3.721358
i:   1800  cost:     3.702366
i:   1900  cost:     3.683494
i:   2000  cost:     3.664674


In [29]:
# Actual y
print(y)

# hypothesis y
print(hypothesis)

[[152.]
 [185.]
 [180.]
 [196.]
 [142.]]
tf.Tensor(
[[154.44199]
 [182.68025]
 [181.58286]
 [196.30276]
 [139.90674]], shape=(5, 1), dtype=float32)
