<a href="https://colab.research.google.com/github/juyounLee/DeepLearningZeroToAll_TF2./blob/main/06_01_softmax_classfier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [77]:
import tensorflow as tf
import numpy as np
import math

In [78]:
# data

x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

x_data = np.array(x_data, dtype=np.float32)
y_data = np.array(y_data, dtype=np.float32)

In [79]:
dataset = tf.data.Dataset.from_tensor_slices((x_data, y_data)).batch(len(x_data))

In [80]:
# initialize the variables

W = tf.Variable(tf.random.normal([4, 3]))
b = tf.Variable(tf.random.normal([3]))

print(W)
print(W.shape)

<tf.Variable 'Variable:0' shape=(4, 3) dtype=float32, numpy=
array([[ 0.7266665 , -1.9571123 ,  1.1303487 ],
       [ 0.1268285 , -0.6014654 , -0.29454297],
       [-0.17672351,  1.2872624 , -0.9154209 ],
       [ 1.1632898 , -0.3690995 , -0.2027912 ]], dtype=float32)>
(4, 3)


In [81]:
# hypothesis
def hypothesis(x):
  hypothesis = tf.matmul(x, W) + b
  return hypothesis

print(hypothesis([[1., 2., 1., 1.]]))

tf.Tensor([[ 3.3089898 -3.2233095 -0.7119629]], shape=(1, 3), dtype=float32)


In [82]:
# softmax
def softmax(x):
  hypo = hypothesis(x)
  y_estimate = tf.nn.softmax(hypo)
  return y_estimate

print(softmax([[1., 2., 1., 1.]]))

tf.Tensor([[0.98097736 0.00142797 0.01759468]], shape=(1, 3), dtype=float32)


In [83]:
# cost function
def cost_fn(x, y):
  y_estimate = softmax(x)
  cost = -tf.reduce_mean(tf.reduce_sum(y*tf.math.log(y_estimate), axis=1))
  return cost

In [84]:
def grad(x, y):
  with tf.GradientTape() as tape:
    loss_value = cost_fn(x, y)
  return tape.gradient(loss_value, [W, b])

In [85]:
optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)

In [86]:
for step in range(3001):
  for feature, label in iter(dataset):
    grads = grad(feature, label)
    optimizer.apply_gradients(grads_and_vars=zip(grads, [W, b]))
    cost = cost_fn(feature, label)

    if step%300 == 0:
      print('step: {} cost:{:.5f}'.format(step, cost.numpy()))

step: 0 cost:6.08215
step: 300 cost:0.83358
step: 600 cost:0.69458
step: 900 cost:0.62367
step: 1200 cost:0.57804
step: 1500 cost:0.54474
step: 1800 cost:0.51857
step: 2100 cost:0.49701
step: 2400 cost:0.47864
step: 2700 cost:0.46257
step: 3000 cost:0.44822


In [88]:
# predict
sample_data = [[2,1,3,2]]
sample_data = np.array(sample_data, dtype=np.float32)

y_estimate = softmax(sample_data)
print(tf.argmax(y_estimate, 1))

tf.Tensor([2], shape=(1,), dtype=int64)
