<a href="https://colab.research.google.com/github/juyounLee/DeepLearningZeroToAll_TF2./blob/main/07_01_03_normalize.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import math
import numpy as np

In [2]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

In [3]:
# normalize function
def normal_fn(xy):
  numirator = xy - np.min(xy, 0)
  denominator = np.max(xy, 0) - np.min(xy, 0)
  return numirator / denominator

xy = normal_fn(xy)
print(xy)

[[1.         1.         0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881783 0.83755792]
 [0.54412549 0.50274824 0.57608696 0.60646801 0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.4258239  0.30434783 0.58504805 0.42624401]
 [0.49556179 0.4258239  0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]


In [4]:
x = np.array(xy[:, :-1], dtype=np.float32)
y = np.array(xy[:, [-1]], dtype=np.float32)

In [5]:
dataset = tf.data.Dataset.from_tensor_slices((x, y)).batch(len(x))

In [6]:
# initialize the variables
W = tf.Variable(tf.random.normal([4, 1]))
b = tf.Variable(tf.random.normal([1]))

In [7]:
def linear_reg_fn(x):
  hypothesis = tf.matmul(x, W) + b
  return hypothesis


In [8]:
def cost_fn(x, y):
  cost = tf.reduce_mean(tf.math.square(linear_reg_fn(x)-y))
  return cost

In [9]:
optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)

In [10]:
def grad_fn(x, y):
  with tf.GradientTape() as tape:
    cost = cost_fn(x, y)
  return tape.gradient(cost, [W, b])

In [11]:
for step in range(2001):
  for feature, label in iter(dataset):
    cost = cost_fn(feature, label)
    grads = grad_fn(feature, label)
    optimizer.apply_gradients(grads_and_vars=zip(grads, [W, b]))

    if step%200==0:
      print('step: {} cost: {:.5f}'.format(step, cost.numpy()))
    

step: 0 cost: 0.72817
step: 200 cost: 0.00792
step: 400 cost: 0.00415
step: 600 cost: 0.00315
step: 800 cost: 0.00288
step: 1000 cost: 0.00281
step: 1200 cost: 0.00279
step: 1400 cost: 0.00279
step: 1600 cost: 0.00278
step: 1800 cost: 0.00278
step: 2000 cost: 0.00278


In [12]:
# predict
y_predict = linear_reg_fn(x)
print(y_predict)

accuracy = tf.reduce_mean(tf.math.square(y_predict-y))
print('Accuracy: {:.5f}'.format(accuracy))

tf.Tensor(
[[0.9844896 ]
 [0.82435966]
 [0.63243806]
 [0.41102272]
 [0.5597631 ]
 [0.46254936]
 [0.14996538]
 [0.01677664]], shape=(8, 1), dtype=float32)
Accuracy: 0.00278
